### ISSUE TITLE
Where are the three columns?

### ISSUE THREAD

**Issue by benkasminbullock** [yi-bai/ids#1]
The README.md says "Each file contains 3 columns: first column is character, second and third column each contains a semi-colon seperated list of IDS sequences." But looking at 

https://raw.githubusercontent.com/yi-bai/ids/main/ids_lv0.txt

there are only two columns.

**Comment by yi-bai** [comment]
@benkasminbullock 

Third column is optional, it only shows up when there is alternative IDS sequences.
e.g.

`屡	⿸尸娄.(.);⿸尸娄T(T)	⿸屎.女(.);⿸屎T女(T)`

**Comment by benkasminbullock** [comment]
OK thanks.
