### ISSUE TITLE
What to do with the missing characters like 𢆉?

### ISSUE THREAD

**Issue by lancejpollard** [yi-bai/ids#3]
On my computer many of the characters on the left and on the right (the radicals/strokes) are showing up as ? question marks with a box around it, signifiying it's not there (in the terminal). Like this one 𢆉. What should I do with that? Can I get all characters to show up somehow? Thank you.

- https://raw.githubusercontent.com/yi-bai/ids/main/ids_lv0.txt
- https://babelstone.co.uk/CJK/IDS.TXT (same issue here)

P.S. How did you create this list? Is there an alternative way I can get a list of all radicals/strokes for each CJK Chinese character? I haven't been able to find a way.

**Comment by unext-bai** [comment]
1. You must install a font supporting all CJKUI to have them displayed correctly, this is one of them:
https://github.com/yuleshow/chinese-fonts/tree/master/%E5%BC%80%E5%BF%83%E5%AE%8B%E4%BD%933.0

2. The break down of CJKUI are done manually, and some programs to normalize and optimize them (not available in this repo).

**Comment by yi-bai** [comment]
1. You must install a font supporting all CJKUI to have them displayed correctly, this is one of them:
https://github.com/yuleshow/chinese-fonts/tree/master/%E5%BC%80%E5%BF%83%E5%AE%8B%E4%BD%933.0

2. The break down of CJKUI are done manually, and some programs to normalize and optimize them (not available in this repo).
